### PR TITLE
Dry up element declaration by aliasing method definition.

### PR DESCRIPTION
**Pull request by asehra**

### CODE REVIEW

**Comment by lashd** [comment]
Thanks @asehra, this looks good. We currently don't have a test to say that that the element types in the `TYPES` can be used to define `Element`s. It would be good to have a solution to this. What do you think we should do here?

**Comment by asehra** [comment]
@lashd This might be a good candidate for acceptance test suite. Something that massages the public interface from an end user's perspective. It could be cucumber or simply Rspec acceptance tests.

**Comment by asehra** [comment]
Eg:

```cucumber
Scenario: Accessing text_field on page
  Given a page with DOM:
    """
      <input type="text" id="country" name="country" value="Germany">
    """
  And a page_magic class
    """
      class PageWithTextField
        include PageMagic
        textfield :country, id: :country
      end
    """
  When I run a session as:
    """
      session = PageMagic.session(browser: :chrome)
      session.visit(PageWithTextField)
      puts session.country.value
    """
  Then I should be see 'Germany' printed on the console
```

**Comment by lashd** [comment]
Hi @asehra I seem to have messed up the merge on the command line such that Githubs UI is not showing this as merged but rest assured, I have merged it in to develop.

**Pull request closed without merging**
